### ISSUE TITLE
Would you be open to sharing some examples to explain how you built pycurl on windows?

### ISSUE THREAD

**Issue by Alex-ley-scrub** [cgohlke/pyicu-build#1]
Hi Christoph,

Firstly I want to say a HUGE thank you from myself and from hundreds/thousands/more?! of people who have benefited from your Windows python wheels for a huge number of packages that are otherwise extremely painful to install.

You clearly have a wealth of experience building these packages on what is arguably the most complicated OS to build packages from source.

This repo is for PyICU and not PyCurl but I have downloaded (and still actively use) both (and many more) from your site in the past. E.g.:
https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycurl

I wanted to try and submit a PR to the pycurl repository to help fix the (more recent) lack of Windows binaries:
https://github.com/pycurl/pycurl/issues/657

But I thought that it would be much more efficient to ask for some examples from you if you had them handy before going down this rabbit hole.

I am hopeful that I could copy much of the approach taken in this repo but with some tweaks for pycurl/libcurl in order to build it from source. Given your experience do you think that is realistic? Would you be able to share some examples of how your built pycurl in the past?

Thank you very much

**Comment by cgohlke** [comment]
I think the same approach taken in this repository will work for pycurl: download [pycurl sources](https://github.com/pycurl/pycurl/tags) and official [curl binaries](https://curl.se/windows/), then build and link pycurl against the curl library. One might have to patch the pycurl setup.py to find the curl link library. Usually I build curl and all dependencies from source using Visual Studio, but that should not be required.
